# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeaeafcd1fe008005f1e518db749c3b451b715811045c5131e47a1ab747600c48d88aae86833517b1d5d4300de46845b2c8e90fa3dcb6c474cf74a99c94ab2ef

test:
  secret_key_base: 7247fce4a1e1bc72cd1c11f96f598c9b7bef499be77cd86af662fb1aa04d78e68b727e089ff6026bbf2d15656ef76c05f18816346e0479d9dc188c75b0bc8092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
